name: dslink_dart_leapmotion
description: A DSLink publishing LeapMotion telemetry to DSA
dependencies:
  crypto: any
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  leap_motion:
    git: https://github.com/kaendfinger/LeapMotionDart.git
